dubbo:
  application:
    name: admin
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
fdfs:
  so-timeout: 1500 # 读取时间
  connect-timeout: 600 # 连接超时
  pool:
    jmx-enabled: false
  # 缩略图
  thumb-image:
    width: 100
    height: 100
  # 服务器地址加端口号呐
  tracker-list: